name: Deployment

on:
  push:
    branches: [main]

job:
  deploy: 
    name: Deploy
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Setting up GO
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Building Codebase Binary
        run: ./scripts/buildprod.sh